version: "3"

services:
  app:
    build: .
    container_name: 'qualix-app'
    ports:
      - '80:80'
    links:
      - db
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated
      - storage-framework:/var/www/storage/framework
      - cache:/var/www/bootstrap/cache
      - vendor:/var/www/vendor

  composer:
    image: composer:1.8
    container_name: 'qualix-composer'
    restart: 'no'
    entrypoint: bash -c "composer install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts --prefer-dist --no-suggest && cp -r vendor/* /vendor-copy-to-host"
    volumes:
      - .:/app:delegated
      - vendor:/app/vendor
      - ./vendor:/vendor-copy-to-host

  db:
    image: mariadb:10.3
    container_name: 'qualix-db'
    environment:
      - MYSQL_DATABASE=qualix
      - MYSQL_ROOT_PASSWORD=will-be-randomized-and-output-on-the-console
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=qualix
      - MYSQL_PASSWORD=qualix

  node:
    image: node:11.13.0
    container_name: 'qualix-npm'
    working_dir: '/app'
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - ./node_modules:/node_modules-copy-to-host
      - ./public:/app/public:delegated
    entrypoint: /bin/sh -c "npm install && cp -r node_modules/* /node_modules-copy-to-host && npm run watch"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'qualix-phpmyadmin'
    ports:
      - '8081:80'
    links:
      - db

volumes:
  storage-framework:
  cache:
  vendor:
  node_modules:
