// For now this mapping is just manually copied from the output of _colors.scss
const colors = {
  'blue': { color: '#3490dc', contrastColor: '#fff' },
  'blue-light': { color: '#8bc0eb', contrastColor: '#fff' },
  'indigo': { color: '#6574cd', contrastColor: '#fff' },
  'indigo-light': { color: '#b2bae6', contrastColor: '#fff' },
  'purple': { color: '#9561e2', contrastColor: '#fff' },
  'purple-light': { color: '#cfb7f2', contrastColor: '#000' },
  'pink': { color: '#f66D9b', contrastColor: '#fff' },
  'pink-light': { color: '#fccddd', contrastColor: '#000' },
  'red': { color: '#e3342f', contrastColor: '#fff' },
  'red-light': { color: '#ef8c89', contrastColor: '#000' },
  'orange': { color: '#f6993f', contrastColor: '#fff' },
  'orange-light': { color: '#fbcda0', contrastColor: '#000' },
  'yellow': { color: '#ffed4a', contrastColor: '#000' },
  'yellow-light': { color: '#fff7b0', contrastColor: '#000' },
  'green': { color: '#38c172', contrastColor: '#fff' },
  'green-light': { color: '#84dba9', contrastColor: '#000' },
  'teal': { color: '#4dc0b5', contrastColor: '#fff' },
  'teal-light': { color: '#98dbd4', contrastColor: '#000' },
  'cyan': { color: '#6cb2eb', contrastColor: '#fff' },
  'cyan-light': { color: '#c6e1f7', contrastColor: '#000' },
  'white': { color: '#fff', contrastColor: '#000' },
  'gray-100': { color: '#f8f9fa', contrastColor: '#000' },
  'gray-200': { color: '#e9ecef', contrastColor: '#000' },
  'gray-300': { color: '#dee2e6', contrastColor: '#000' },
  'gray-400': { color: '#ced4da', contrastColor: '#000' },
  'gray-500': { color: '#adb5bd', contrastColor: '#fff' },
  'gray-600': { color: '#6c757d', contrastColor: '#fff' },
  'gray-700': { color: '#495057', contrastColor: '#fff' },
  'gray-800': { color: '#343a40', contrastColor: '#fff' },
  'gray-900': { color: '#212529', contrastColor: '#fff' },
  'black': { color: '#000', contrastColor: '#fff' },
}

export default colors;
