name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  output-ssh-known-hosts:
    runs-on: ubuntu-latest
    environment: gryfensee
    steps:
      - run: 'ssh-keyscan qualix.gryfensee.ch'
      - run: 'ssh-keyscan qualix.flamberg.ch'
